name: deploy-function

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12'
  FUNCTION_CODE_DIR: ./
  AZURE_FUNCTION_APP_PACKAGE_NAME: 'function_app_package.zip'
  AZURE_FUNCTION_APP_PACKAGE_FULL_PATH: '${{ github.workspace }}/function_app_package.zip'

jobs:
  deploy-function:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Zip function app content
      run: |
        sudo apt-get update && sudo apt-get install -y zip
        zip -r ${{ env.AZURE_FUNCTION_APP_PACKAGE_NAME }} function_app.py host.json requirements.txt src/common/ src/silver/ src/bronze/
      working-directory: ${{ env.FUNCTION_CODE_DIR }}

    - name: Deploy Function App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_FUNCTION_APP_NAME }} 
        slot-name: 'production'
        package: ${{ env.AZURE_FUNCTION_APP_PACKAGE_FULL_PATH }}

    - name: Logout from Azure
      run: az logout
      if: always()
