name: cv demo1 CI/CD orchestrator

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - './'
      - '.github/workflows/main.yml'
  workflow_dispatch:

jobs:
  deploy-dev:
    name: "Deploy DEV"
    uses: ${{ github.repository }}/.github/workflows/deploy-dev.yml@main

  deploy-prod:
    name: "Deploy PROD"
    needs: deploy-dev
    uses: ${{ github.repository }}/.github/workflows/deploy-prod.yml@main
