name: actions cv-demo1

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - './'
      - '.github/workflows/main-ci-cd.yml'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12'
  FUNCTION_APP_OS: linux
  TERRAFORM_DIR: ./infra
  FUNCTION_CODE_DIR: ./
  # Zdefiniuj ścieżkę do pliku ZIP. Ustawiamy go w katalogu głównym repozytorium.
  AZURE_FUNCTION_APP_PACKAGE_NAME: 'function_app_package.zip' # Tylko nazwa pliku
  AZURE_FUNCTION_APP_PACKAGE_FULL_PATH: '${{ github.workspace }}/function_app_package.zip' # Pełna ścieżka

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      function_app_name: ${{ steps.tf_outputs.outputs.function_app_name }}
      resource_group_name: ${{ steps.tf_outputs.outputs.resource_group_name }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 'Login to Azure for Terraform'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Export Azure credentials for Terraform
      run: |
        echo "ARM_CLIENT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.TERRAFORM_DIR }}

    - name: Terraform Validate
      run: terraform validate
      working-directory: ${{ env.TERRAFORM_DIR }}

    - name: Terraform Plan
      id: plan
      run: |
        # Uruchamiamy planowanie i zapisujemy wynik do zmiennej.
        # W zależności od wyjścia, ustawiamy zmienną w GitHub Actions.
        terraform plan -no-color -input=false -out=tfplan > plan_output.txt
        PLAN_OUTPUT=$(cat plan_output.txt)
        echo "$PLAN_OUTPUT"

        if grep -q "No changes. Your infrastructure matches the configuration." plan_output.txt; then
          echo "::set-output name=has_changes::false"
        else
          echo "::set-output name=has_changes::true"
        fi
      working-directory: ${{ env.TERRAFORM_DIR }}

    # --- Zmodyfikowany krok Terraform Apply ---
    - name: Terraform Apply
      id: apply
      # Zmieniamy warunek na sprawdzanie, czy plan wykrył zmiany
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.plan.outputs.has_changes == 'true' }}
      run: terraform apply -input=false -auto-approve tfplan
      working-directory: ${{ env.TERRAFORM_DIR }}

    - name: Get Terraform Outputs
      id: tf_outputs
      run: |
        FUNCTION_APP_NAME=$(terraform output -raw function_app_name)
        RESOURCE_GROUP_NAME=$(terraform output -raw resource_group_name)
        STORAGE_ACCOUNT_NAME=$(terraform output -raw storage_account_name)
        STORAGE_CONTAINER_NAME=$(terraform output -raw configs_container_name )
        EVENTGRID_TOPIC_NAME=$(terraform output -raw eventgrid_topic_name)

        echo "FUNCTION_APP_NAME=$FUNCTION_APP_NAME" >> $GITHUB_ENV
        echo "RESOURCE_GROUP_NAME=$RESOURCE_GROUP_NAME" >> $GITHUB_ENV
        echo "STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME" >> $GITHUB_ENV
        echo "STORAGE_CONTAINER_NAME=$STORAGE_CONTAINER_NAME" >> $GITHUB_ENV
        echo "EVENTGRID_TOPIC_NAME=$EVENTGRID_TOPIC_NAME" >> $GITHUB_ENV

        echo "function_app_name=$FUNCTION_APP_NAME" >> $GITHUB_OUTPUT
        echo "resource_group_name=$RESOURCE_GROUP_NAME" >> $GITHUB_OUTPUT
        echo "storage_account_name=$STORAGE_ACCOUNT_NAME" >> $GITHUB_OUTPUT
        echo "storage_container_name=$STORAGE_CONTAINER_NAME" >> $GITHUB_OUTPUT
        echo "eventgrid_topic_name=$EVENTGRID_TOPIC_NAME" >> $GITHUB_OUTPUT
      working-directory: ${{ env.TERRAFORM_DIR }}

    - name: Logout from Azure (Terraform)
      run: az logout
      if: always()

  deploy-function:
    runs-on: ubuntu-latest
    needs: terraform
    if: success()
    env:
      FUNCTION_APP_NAME: ${{ needs.terraform.outputs.function_app_name }}
      RESOURCE_GROUP_NAME: ${{ needs.terraform.outputs.resource_group_name }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Zip function app content # <-- Zmieniamy sposób pakowania
      run: |
        sudo apt-get update && sudo apt-get install -y zip
        # Pakujemy zawartość katalogu z kodem do pliku ZIP w głównym katalogu repozytorium
          zip -r ${{ env.AZURE_FUNCTION_APP_PACKAGE_NAME }} . -x ".git*" -x ".vscode*"
      working-directory: ${{ env.FUNCTION_CODE_DIR }} # Upewnij się, że pakujesz z ./ (katalogu z kodem)

    - name: List files in current directory # <-- KROK DIAGNOSTYCZNY
      run: ls -la . 

    - name: List files in workspace root # <-- KROK DIAGNOSTYCZNY
      run: ls -la ${{ github.workspace }}

    - name: Deploy Function App using Azure WebApps Deploy Action
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.FUNCTION_APP_NAME }}
        slot-name: 'production'
        package: ${{ env.AZURE_FUNCTION_APP_PACKAGE_FULL_PATH }} # <-- Używamy pełnej ścieżki
        # Wersja runtime Pythona, jeśli potrzebne (ale powinna być w Terraformie)
        # python-version: '${{ env.PYTHON_VERSION }}' # Możesz spróbować, ale już jest w TF

    - name: Logout from Azure (Deployment)
      run: az logout
      if: always()


  # upload-config:
  #   runs-on: ubuntu-latest
  #   needs: 
  #     - terraform
  #     - deploy-function
  #   env:
  #     STORAGE_ACCOUNT_NAME: ${{ needs.terraform.outputs.storage_account_name }}
  #     STORAGE_CONTAINER_NAME: ${{ needs.terraform.outputs.storage_container_name }}
  #     EVENTGRID_TOPIC_NAME: ${{ needs.terraform.outputs.eventgrid_topic_name }}
  #     RESOURCE_GROUP_NAME: ${{ needs.terraform.outputs.resource_group_name }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: azure/login@v2
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}
  #     - name: Upload config.json to Blob Storage
  #       run: |
  #         az storage blob upload \
  #           --account-name "$STORAGE_ACCOUNT_NAME" \
  #           --container-name "$STORAGE_CONTAINER_NAME" \
  #           --file src/common/config/dev.config.json \
  #           --name dev.config.json \
  #           --overwrite \
  #           --auth-mode login
  #     - name: Publish Event to Event Grid
  #       run: |
  #         az eventgrid event publish \
  #           --topic-name "$EVENTGRID_TOPIC_NAME" \
  #           --resource-group "$RESOURCE_GROUP_NAME" \
  #           --event '[
  #             {
  #               "id": "'$(uuidgen)'",
  #               "eventType": "ConfigFileUploaded",
  #               "subject": "/dev.config.json",
  #               "eventTime": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'",
  #               "data": { "filename": "dev.config.json" },
  #               "dataVersion": "1.0"
  #             }
  #           ]'
