name: cv demo1 CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - './'
      - '.github/workflows/main.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Wybierz środowisko do wdrożenia'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

env:
  PYTHON_VERSION: '3.12'
  TERRAFORM_DIR: ./infra
  FUNCTION_CODE_DIR: ./
  AZURE_FUNCTION_APP_PACKAGE_FULL_PATH: '${{ github.workspace }}/function_app_package.zip'

jobs:
  call_deploy_dev:
    name: "Wdrożenie DEV"
    uses: ./.github/workflows/reusable_deploy.yml@main
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
    with:
      environment: dev
    secrets:
      azure_credentials: ${{ secrets.AZURE_DEV_CREDENTIALS }}

  call_deploy_prod:
    name: "Wdrożenie PROD"
    uses: ./.github/workflows/reusable_deploy.yml@main
    if: github.event.inputs.environment == 'prod'
    with:
      environment: prod
    secrets:
      azure_credentials: ${{ secrets.AZURE_PROD_CREDENTIALS }}