name: Upload Config to Azure Blob Storage

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/common/config/dev.config.json'

env:
  TERRAFORM_DIR: ./infra

jobs:
  upload-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TERRAFORM_DIR }}

      - name: Terraform Refresh
        run: terraform refresh
        working-directory: ${{ env.TERRAFORM_DIR }}

      - name: Get Terraform Outputs
        id: tf_outputs
        run: |
          echo "STORAGE_ACCOUNT_NAME=$(terraform output -raw storage_account_name)" >> $GITHUB_ENV
          echo "STORAGE_CONTAINER_NAME=$(terraform output -raw configs_container_name)" >> $GITHUB_ENV
          echo "RESOURCE_GROUP_NAME=$(terraform output -raw resource_group_name)" >> $GITHUB_ENV
          echo "EVENTGRID_TOPIC_NAME=$(terraform output -raw eventgrid_topic_name || echo '')" >> $GITHUB_ENV
        working-directory: ${{ env.TERRAFORM_DIR }}

      - name: Upload config.json to Blob Storage
        run: |
          az storage blob upload \
            --account-name "$STORAGE_ACCOUNT_NAME" \
            --container-name "$STORAGE_CONTAINER_NAME" \
            --file src/common/config/dev.config.json \
            --name dev.config.json \
            --overwrite \
            --auth-mode login

      - name: Publish Event to Event Grid
        if: env.EVENTGRID_TOPIC_NAME != ''
        run: |
          az eventgrid event publish \
            --topic-name "$EVENTGRID_TOPIC_NAME" \
            --resource-group "$RESOURCE_GROUP_NAME" \
            --event '[{
              "id": "'$(uuidgen)'",
              "eventType": "ConfigFileUploaded",
              "subject": "/dev.config.json",
              "eventTime": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'",
              "data": { "filename": "dev.config.json" },
              "dataVersion": "1.0"
            }]'

      - name: Logout from Azure
        run: az logout
        if: always()
