from enum import Enum, auto


class ModelType(Enum):
    COUNTRY = "COUNTRY"
    GRADUATE_UNEMPLOYMENT = "GRADUATE_UNEMPLOYMENT"
    NOBEL_LAUREATES = "NOBEL_LAUREATES"
    PATENTS = "PATENTS"
    RD_EXPENDITURE = "RD_EXPENDITURE"
    RESEARCHERS = "RESEARCHERS"
    PKB = "PKB"